"""Add foreign key to Price table for Market

Revision ID: e8eb702b6a9c
Revises: d821671317ca
Create Date: 2025-02-23 19:25:47.482402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eb702b6a9c'
down_revision = 'd821671317ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_price_market', 'market', ['market_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('market_id')

    # ### end Alembic commands ###
